---
- name: Computer configuration
  hosts: win
  tags: ["computerconfig_play"]

  vars_files:
    - default.config.yml

### Override default.config.yml ###

  pre_tasks:
    - name: Include playbook user configuration.
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

### Put all handlers here ###

  handlers:
    - name: Configure Firewall rules (RDS).
      ansible.windows.win_shell: >
        "{{ 'Enable-NetFirewallRule' if remote_desktop_enabled else 'Disable-NetFirewallRule' }}
        -DisplayGroup 'Remotedesktop'"


  tasks:

    - name: Enable administrator.
      ansible.builtin.import_tasks:
        file: tasks/administrator.yml
      when: install_windows_updates
      tags: ["administrator"]

    - name: Set timezone
      ansible.builtin.import_tasks:
        file: tasks/timezone.yml
      when: set_timezone
      tags: ["timezone"]

    - name: Include windows updates configuration.
      ansible.builtin.import_tasks:
        file: tasks/updates.yml
      when: install_windows_updates
      tags: ["updates"]

    - name: Include chocolatey configuration.
      ansible.builtin.import_tasks:
        file: tasks/chocolatey.yml
      when: install_chocolatey_packages
      tags: ["choco"]

    - name: Include explorer configuration.
      ansible.builtin.import_tasks:
        file: tasks/explorer.yml
      when: configure_explorer
      tags: ["explorer"]

    - name: Include taskbar configuration.
      ansible.builtin.import_tasks:
        file: tasks/taskbar.yml
      when: configure_taskbar
      tags: ["taskbar"]

    - name: Include start menu configuration.
      ansible.builtin.import_tasks:
        file: tasks/start_menu.yml
      when: configure_start_menu
      tags: ["start_menu"]

    - name: Include mouse configuration.
      ansible.builtin.import_tasks:
        file: tasks/mouse.yml
      when: disable_mouse_acceleration
      tags: ["mouse"]

    - name: Map public drive
      ansible.builtin.import_tasks:
        file: tasks/map_public.yml
      when: map_drive
      tags: ["map_public"]

    - name: Install prt-gdc-kyocera01
      ansible.builtin.import_tasks:
        file: tasks/prt_kyocera01.yml
      when: install_kyocera
      tags: ["prt_kyocera01"]

    - name: Install prt-gdc-imagerunner01
      ansible.builtin.import_tasks:
        file: tasks/prt_imagerunner01.yml
      when: install_kyocera
      tags: ["prt_imagerunner01"]

    - name: Add new account
      ansible.builtin.import_tasks:
        file: tasks/new_account.yml
      when: add_new_account
      tags: ["new_account"]

    - name: Include hostname configuration.
      ansible.builtin.import_tasks:
        file: tasks/hostname.yml
      when: configure_hostname
      tags: ["hostname"]



- name: Provisioning new user
  hosts: win
  tags: ["user_config_play"]

  vars:
    ansible_user: "{{ win_user_name }}"
    ansible_password: "{{ win_password }}"

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook user configuration.
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  tasks:

    - name: Install rms
      ansible.builtin.import_tasks:
        file: tasks/rms.yml
      when: install_rms
      tags: ["rms"]

    - name: Include debloat configuration.
      ansible.builtin.import_tasks:
        file: tasks/debloat.yml
      when: remove_bloatware
      tags: ["debloat_user"]

    - name: Include explorer configuration.
      ansible.builtin.import_tasks:
        file: tasks/explorer.yml
      when: configure_explorer
      tags: ["explorer_user"]

    - name: Include taskbar configuration.
      ansible.builtin.import_tasks:
        file: tasks/taskbar.yml
      when: configure_taskbar
      tags: ["taskbar_user"]

    - name: Include start menu configuration.
      ansible.builtin.import_tasks:
        file: tasks/start_menu.yml
      when: configure_start_menu
      tags: ["start_menu_user"]

    - name: Include power plan configuration.
      ansible.builtin.import_tasks:
        file: tasks/power_plan.yml
      when: change_power_plan
      tags: ["power"]

    - name: Map network drive
      ansible.builtin.import_tasks:
        file: tasks/map_accounting_drive.yml
      when: map_accounting_drive
      tags: ["map_accounting_drive"]

    - name: file explorer shortcut to desktop
      ansible.builtin.import_tasks:
        file: tasks/add_explorer_shortcut.yml
      when: add_explorer_shortcut
      tags: ["add_explorer_shortcut"]

    - name: add sage rdp
      ansible.builtin.import_tasks:
        file: tasks/sage_rdp.yml
      when: sage_rdp
      tags: ["sage_rdp"]