---
- name: install Install prt-gdc-imagerunner01-purchasing-11x7
  win_shell: pnputil /add-driver "\\192.168.1.10\Public\Software\ImageRunner-ADV4525\x64\etc\CNP60MA64.INF" /install

- name: add printer port
  win_shell: Add-PrinterPort -Name "{{ IRPrinterPortName }}" -PrinterHostAddress "{{ IRPrinterIP }}"

- name: add printer driver
  win_shell: Add-PrinterDriver -Name "{{ IRPrintDriverName  }}" # if this string is not known, grab from .inf file

- name: add printer
  win_shell: Add-Printer -Name "{{ IRPrinterName }}" -DriverName "{{ IRPrintDriverName }}" -PortName "{{ IRPrinterPortName }}"

- name: black and white printing
  win_shell: Set-PrintConfiguration -PrinterName "{{ IRPrinterName }}" -Color 0 # B&W

- name: single-sided printing
  win_shell: Set-PrintConfiguration -PrinterName "{{ IRPrinterName }}" -DuplexingMode 'OneSided'

- name: default letter papersize
  win_shell: Set-PrintConfiguration -PrinterName "{{ IRPrinterName }}" -PaperSize 'Letter'
